name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # Step 3: Build and push image
      - name: Build and push image
        run: |
          sudo aws ecr get-login-password --region eu-west-2 | sudo docker login -u AWS -p $(aws ecr get-login-password --region eu-west-2) 010526243714.dkr.ecr.eu-west-2.amazonaws.com
          sudo docker pull nginx:latest
          sudo docker tag nginx:latest 010526243714.dkr.ecr.eu-west-2.amazonaws.com/learn:$GITHUB_RUN_NUMBER
          sudo docker push 010526243714.dkr.ecr.eu-west-2.amazonaws.com/learn:$GITHUB_RUN_NUMBER

      # # Step 4: Set Up SSH Key
      # - name: Set Up SSH Key
      #   run: |
      #     cd ~
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_KEY }}" > ~/.ssh/noorulqumar0_github
      #     chmod 600 ~/.ssh/noorulqumar0_github
      #     eval "$(ssh-agent -s)"
      #     ssh-add ~/.ssh/noorulqumar0_github
      #     cat ~/.ssh/noorulqumar0_github
          
      # Step 5: Clone the repository
      - name: Clone the repository
        run: |
          cd 
          git clone https://github.com/noorulqumar/ArgoCD-manifest-file.git
          ls

      # Step 5: Update the deployment image
      - name: Update deployment image
        run: |
          cd 
          cd ArgoCD-manifest-file
          IMAGE=010526243714.dkr.ecr.eu-west-2.amazonaws.com/learn:$GITHUB_RUN_NUMBER
          sed -i "s|image:.*|image: ${IMAGE}|" green-deployment/deployment.yml
          echo "Updated image to ${IMAGE}"
          cat green-deployment/deployment.yml

      - name: Push Updated Image tag
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "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"
          add_timestamp: true
          commit_prefix: "[AUTO]"
          commit_message: "Automatic commit"
          force: false
          target_branch: update/version

      # # Step 6: Commit and push changes
      # - name: Commit and push changes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     cd ArgoCD-manifest-file
      #     git config --local user.name "noorulqumar"
      #     git config --local user.email "noorulqumar0@gmail.com"
      #     git status
      #     git add green-deployment/deployment.yml
      #     git commit -m "Update deployment image to ${IMAGE}"
      #     git remote -v
      #     git status
      #     git push origin main

