
name: Deploy to Amazon ECS triggered from push to main branch

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-2

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "AKIAQE43JXOBDOSYAQIH"
          aws-secret-access-key: "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"
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          sudo aws ecr get-login-password --region eu-west-2 | sudo docker login -u AWS -p $(aws ecr get-login-password --region eu-west-2) 010526243714.dkr.ecr.eu-west-2.amazonaws.com

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker pull nginx:latest
          docker tag nginx:latest 010526243714.dkr.ecr.eu-west-2.amazonaws.com/learn:latest
          docker push 010526243714.dkr.ecr.eu-west-2.amazonaws.com/learn:latest
